const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const env={DB:{prepare(q){let a=[];const st=sql.prepare(q);return {bind(...v){a=v;return this},async first(){return st.get(...a)||null},async all(){return {results:st.all(...a)}},async run(){return st.run(...a)}}}},BUCKET:{async put(){},async delete(){},async get(){return null}}};
let upstreamCalls=0,moderationEmpty=false,imageTimeout=false;
const route={};
const jobs={};const context={exports:route,require:n=>n==='cloudflare:workers'?{env}:n==='../jobs'?jobs:require(n),Response,Request,Headers,URL,TextDecoder,Uint8Array,atob,crypto,AbortSignal,fetch:async(url)=>{upstreamCalls++;if(imageTimeout&&url.endsWith('/images/generations'))throw Object.assign(Error('simulated timeout'),{name:'TimeoutError'});return Response.json({results:moderationEmpty?[]:[{flagged:false}],data:[{b64_json:'iVBORw0KGgoTEST'}]})}};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/sg/jobs.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{...context,exports:jobs});
vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/sg/[...path]/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);
const req=(p,b,id='u',origin='https://example.test')=>new Request('https://example.test/api/sg/'+p,{method:b?'POST':'GET',headers:{...(id?{'oai-authenticated-user-id':id}:{}),origin,'content-type':'application/json'},...(b?{body:JSON.stringify(p==='generate'?{requestId:crypto.randomUUID(),...b}:b)}:{})});
(async()=>{
assert.equal((await route.GET(req('status',null,null))).status,401);
assert.equal((await route.POST(req('generate',{prompt:'flower'},'u','https://evil.test'))).status,403);
assert.equal((await route.POST(req('generate',{prompt:'flower'}))).status,503);assert.equal(upstreamCalls,0);
env.OPENAI_API_KEY='test-only';env.GENERATION_ENABLED='true';env.GENERATION_DAILY_LIMIT='100';
assert.equal((await route.POST(req('generate',{prompt:'a'}))).status,400);
for(let i=0;i<10;i++)assert.equal((await route.POST(req('generate',{prompt:'flower'}))).status,200);
assert.equal((await route.POST(req('generate',{prompt:'flower'}))).status,429);assert.equal(upstreamCalls,20);
const beforeDuplicate=upstreamCalls;const requestId=crypto.randomUUID();assert.equal((await route.POST(req('generate',{prompt:'new flower',requestId},'u2'))).status,200);assert.equal((await route.POST(req('generate',{prompt:'new flower',requestId},'u2'))).status,409);assert.equal(upstreamCalls,beforeDuplicate+2);
moderationEmpty=true;assert.equal((await route.POST(req('generate',{prompt:'new flower'},'u3'))).status,502);assert.equal(upstreamCalls,beforeDuplicate+3);moderationEmpty=false;
const timeoutId=crypto.randomUUID();imageTimeout=true;const beforeTimeout=upstreamCalls;
assert.equal((await route.POST(req('generate',{prompt:'timeout flower',requestId:timeoutId},'timeout-user'))).status,502);
assert.equal(sql.prepare('SELECT state FROM generation_requests WHERE user=? AND id=?').get('timeout-user',timeoutId).state,'unknown');
assert.equal((await route.POST(req('generate',{prompt:'timeout flower',requestId:timeoutId},'timeout-user'))).status,409);
assert.equal(upstreamCalls,beforeTimeout+2);imageTimeout=false;
env.GENERATION_DAILY_LIMIT='1';const beforeCap=upstreamCalls;assert.equal((await route.POST(req('generate',{prompt:'new flower'},'u4'))).status,429);assert.equal(upstreamCalls,beforeCap);
assert.equal((await (await route.GET(req('status'))).json()).remaining,0);
assert.equal((await route.POST(req('publish',{consent:true,title:'test',image:'data:image/png;base64,aGVsbG8='}))).status,400);assert.equal(upstreamCalls,beforeCap);
sql.prepare('INSERT INTO posts VALUES(?,?,?,?,?,0)').run('p','other','title','key',Date.now());
assert.equal((await (await route.GET(req('feed?post=p'))).json()).posts.length,1);
assert.equal((await (await route.GET(req('feed?post=missing'))).json()).posts.length,0);
assert.equal((await route.POST(req('delete',{id:'p'}))).status,403);
assert.equal((await route.POST(req('like',{id:'p',liked:'yes'}))).status,400);
assert.equal((await route.POST(req('like',{id:'p',liked:true}))).status,200);
assert.equal((await route.POST(req('like',{id:'p',liked:true}))).status,200);assert.equal(sql.prepare('SELECT count(*) n FROM likes').get().n,1);
assert.equal((await route.POST(req('block',{id:'p'}))).status,200);
assert.equal((await (await route.GET(req('feed'))).json()).posts.length,0);
console.log('PASS: auth, origin, inactive API, validation, atomic quota, upload format, ownership, idempotent likes, blocked feed. Request deduplication including timeout/unknown outcomes, malformed moderation rejection, usage remaining, global cap. No external API calls.');
})().catch(e=>{console.error(e);process.exitCode=1});
