const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),ts=require('typescript');
const cache={};function read(name){if(cache[name])return cache[name];const out={};cache[name]=out;vm.runInNewContext(ts.transpileModule(fs.readFileSync('server/commerce/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:out,require:n=>n.startsWith('../')?read(n):n.startsWith('./')?read(n.slice(2)):require(n),Buffer,Request,Response,Headers,URL,URLSearchParams,AbortSignal,TextDecoder});return out}
const {commerce}=read('handler'),{verifyPayment}=read('plans');
const settings={APP_ORIGIN:'https://jini-seniorgram.netlify.app',DATABASE_URL:'test-database',KAKAO_REST_API_KEY:'test-key',KAKAO_CLIENT_SECRET:'test-secret',KAKAO_LOGIN_ENABLED:'true',KAKAOPAY_TEST_ENABLED:'true',KAKAOPAY_TEST_SECRET_KEY:'test-pay-secret'};
const states=new Set(),sessions=new Map();let calls=0,queryCalls=0,lastReady=null;const orders=new Map();
const deps={env:k=>settings[k],query:async(q,v=[])=>{queryCalls++;if(q.startsWith('DELETE FROM sg_oauth_states WHERE expires'))return {rows:[]};if(q.startsWith('INSERT INTO sg_oauth_states')){states.add(v[0]);return {rows:[]}}if(q.startsWith('DELETE FROM sg_oauth_states')){const had=states.delete(v[0]);return {rows:had?[{hash:v[0]}]:[]}}if(q.startsWith('INSERT INTO sg_accounts'))return {rows:[{id:'user-1'}]};if(q.startsWith('INSERT INTO sg_sessions')){sessions.set(v[0],v[1]);return {rows:[]}}if(q.startsWith('SELECT a.id'))return {rows:sessions.has(v[0])?[{id:'user-1',nickname:'테스트'}]:[]};if(q.startsWith('DELETE FROM sg_sessions')){sessions.delete(v[0]);return {rows:[]}}if(q.startsWith('SELECT granted'))return {rows:[]};if(q.startsWith('INSERT INTO sg_subscription_orders')){const key=v[1]+v[2];if(orders.has(key))return {rows:[]};const row={id:v[0],account_id:v[1],request_id:v[2],amount:v[4],state:'preparing'};orders.set(key,row);orders.set(v[0],row);return {rows:[{id:v[0]}]}}if(q.startsWith('UPDATE sg_subscription_orders SET state=\'ready\'')){Object.assign(orders.get(v[2]),{state:'ready',tid:v[0],redirect_url:v[1]});return {rows:[]}}if(q.startsWith('SELECT state,redirect_url'))return {rows:[orders.get(v[0]+v[1])]};throw Error('Unexpected SQL '+q)},fetch:async(url,init)=>{calls++;if(url.includes('/oauth/token'))return Response.json({access_token:'PRIVATE_ACCESS_TOKEN'});if(url.includes('/v2/user/me'))return Response.json({id:12345,properties:{nickname:'테스트'}});if(url.endsWith('/payment/ready')){lastReady=JSON.parse(init.body);return Response.json({tid:'test-tid',next_redirect_pc_url:'https://online-payment.kakaopay.com/test'})}throw Error('Unexpected provider call')}};
const origin=settings.APP_ORIGIN;function req(path,{method='GET',body,cookie,requestOrigin=origin}={}){return new Request(origin+path,{method,headers:{...(cookie?{cookie}:{}),...(method==='POST'?{'content-type':'application/json',origin:requestOrigin}:{})},...(body?{body:JSON.stringify(body)}:{})})}
(async()=>{
 let r=await commerce(req('/api/account/config'),deps);const conf=await r.json();assert.equal(conf.checkoutReady,false);assert.equal(conf.trial.requiresCard,false);assert.equal(queryCalls,0);
 r=await commerce(req('/api/auth/kakao/start'),deps);const nonce=new URL(r.headers.get('location')).searchParams.get('state'),oauthCookie='__Host-sg-oauth='+nonce;assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);
 await commerce(req('/api/auth/kakao/callback?state=wrong&code=x',{cookie:oauthCookie}),deps);assert.equal(calls,0);
 r=await commerce(req('/api/auth/kakao/callback?state='+nonce+'&code=x',{cookie:oauthCookie}),deps);assert.equal(calls,2);const sessionCookie=r.headers.get('set-cookie').match(/__Host-sg-session=[A-Za-z0-9_-]+/)[0];assert(!r.headers.get('set-cookie').includes('PRIVATE_ACCESS_TOKEN'));
 await commerce(req('/api/auth/kakao/callback?state='+nonce+'&code=x',{cookie:oauthCookie}),deps);assert.equal(calls,2,'OAuth state can only be consumed once');
 r=await commerce(req('/api/account/me',{cookie:sessionCookie}),deps);assert.equal((await r.json()).user.id,'user-1');
 r=await commerce(req('/api/auth/logout',{method:'POST',cookie:sessionCookie,requestOrigin:'https://evil.test'}),deps);assert.equal(r.status,403);
 r=await commerce(req('/api/billing/checkout',{method:'POST',cookie:sessionCookie,body:{amount:1,planId:'video'}}),deps);assert.equal(r.status,503);assert.equal(calls,2,'Live checkout always closed');
 const id=require('crypto').randomUUID();r=await commerce(req('/api/billing/test-ready',{method:'POST',cookie:sessionCookie,body:{requestId:id,planId:'video',amount:1,testConsent:true}}),deps);assert.equal(r.status,200);assert.equal(lastReady.total_amount,19900,'server determines amount');assert.equal(lastReady.cid,'TCSUBSCRIP','cannot use live merchant');
 await commerce(req('/api/billing/test-ready',{method:'POST',cookie:sessionCookie,body:{requestId:id,planId:'video',testConsent:true}}),deps);assert.equal(calls,3,'duplicate test request is not submitted twice');
 assert.equal(verifyPayment({tid:'t',cid:'c',partner_order_id:'o',partner_user_id:'u',amount:{total:1},sid:'s'},{tid:'t',id:'o',account_id:'u',amount:19900},'c'),false);
 await commerce(req('/api/auth/logout',{method:'POST',cookie:sessionCookie}),deps);r=await commerce(req('/api/account/me',{cookie:sessionCookie}),deps);assert.equal((await r.json()).user,null);
 delete settings.KAKAO_CLIENT_SECRET;r=await commerce(req('/api/auth/kakao/start'),deps);assert.equal(r.status,503);
 console.log('PASS commerce: configuration gates, OAuth state/cookie/replay, session revocation, CSRF, server price, idempotency, receipt mismatch, test-only payment. No real API or DB calls.');
})().catch(e=>{console.error(e);process.exitCode=1});
