const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),ts=require('typescript'),{randomUUID}=require('crypto'),{PGlite}=require('@electric-sql/pglite');
const cache={};function read(file){file=path.resolve(file);if(cache[file])return cache[file];const out={};cache[file]=out;vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:out,require:n=>n.startsWith('.')?read(path.resolve(path.dirname(file),n+'.ts')):require(n),Buffer,Request,Response,Headers,URL,URLSearchParams,AbortSignal,TextDecoder,TextEncoder,Blob,Uint8Array,Date,Error});return out}
const {product}=read('server/product/handler.ts'),{hashToken}=read('server/commerce/security.ts');
(async()=>{
 const db=new PGlite();for(const file of fs.readdirSync('migrations/postgres').filter(f=>f.endsWith('.sql')).sort())await db.exec(fs.readFileSync('migrations/postgres/'+file,'utf8'));
 const ids=[randomUUID(),randomUUID()],tokens=['a'.repeat(43),'b'.repeat(43)];for(let i=0;i<2;i++){await db.query('INSERT INTO sg_accounts(id,kakao_id,nickname) VALUES($1,$2,$3)',[ids[i],String(i+1),'회원'+i]);await db.query("INSERT INTO sg_sessions(hash,account_id,expires_at) VALUES($1,$2,now()+interval '1 day')",[hashToken(tokens[i]),ids[i]])}
 const env={APP_ORIGIN:'https://jini-seniorgram.netlify.app',DATABASE_URL:'test-only',PRODUCT_SCHEMA_VERSION:'3',MEDIA_STORAGE_ENABLED:'true',GENERATION_ENABLED:'true',GENERATION_DAILY_LIMIT:'10',OPENAI_API_KEY:'fake',TRIAL_ENABLED:'true',COMMUNITY_ENABLED:'true'};
 let mode='success',creates=0,moderations=0;const files=new Map(),png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=','base64');
 const d={env:k=>env[k],query:(q,v)=>db.query(q,v),transaction:fn=>db.transaction(tx=>fn((q,v)=>tx.query(q,v))),files:{put:async(k,b)=>files.set(k,new Uint8Array(b).buffer),get:async k=>files.get(k)||null,delete:async k=>files.delete(k)},fetch:async(url,init)=>{
  if(url.endsWith('/moderations')){moderations++;return Response.json({results:[{flagged:mode==='blocked'}]})}
  if(url.endsWith('/responses')){creates++;if(mode==='timeout')throw Error('TIMEOUT');if(mode==='rejected')return new Response('',{status:400});return Response.json({id:'resp_'+creates})}
  if(url.includes('/responses/'))return Response.json({status:'completed',output:[{type:'image_generation_call',result:png.toString('base64')}]});throw Error('Unexpected external request');
 }};
 function request(route,{who=0,body,origin=env.APP_ORIGIN,headers={}}={}){return new Request(env.APP_ORIGIN+route,{method:body?'POST':'GET',headers:{...(who===null?{}:{cookie:'__Host-sg-session='+tokens[who]}),...(body?{'content-type':'application/json',origin}:{}),...headers},body:body?JSON.stringify(body):undefined})}
 const call=(route,options)=>product(request(route,options),d);const json=async(route,options)=>{const r=await call(route,options),body=await r.json();assert(r.ok,JSON.stringify(body));return body};
 assert.equal((await call('/api/account/trial',{body:{consent:true},origin:'https://evil.test'})).status,403);
 assert.equal((await call('/api/sg/jobs',{who:null,headers:{'oai-authenticated-user-id':ids[0]}})).status,401,'untrusted gateway header cannot authenticate');
 await Promise.all([json('/api/account/trial',{body:{consent:true}}),json('/api/account/trial',{body:{consent:true}})]);assert.equal((await json('/api/account/usage')).imagesRemaining,3,'trial awarded exactly once');
 const payload={requestId:randomUUID(),kind:'image',prompt:'귀여운 강아지를 그려줘'};
 const [first,duplicate]=await Promise.all([json('/api/sg/jobs',{body:payload}),json('/api/sg/jobs',{body:payload})]);assert.equal(first.job.id,duplicate.job.id);assert.equal(creates,1,'concurrent requests create only one provider job');assert.equal((await json('/api/account/usage')).imagesRemaining,2);
 assert.equal((await call('/api/sg/jobs/'+first.job.id,{who:1})).status,404,'member isolation');
 const done=await json('/api/sg/jobs/'+first.job.id+'/refresh',{body:{}});assert.equal(done.job.state,'succeeded');let r=await call(done.job.fileUrl);assert.deepEqual(Buffer.from(await r.arrayBuffer()),png);r=await call(done.job.fileUrl,{headers:{range:'bytes=0-7'}});assert.equal(r.status,206);assert.equal((await r.arrayBuffer()).byteLength,8);assert.equal((await call(done.job.fileUrl,{who:1})).status,404);
 r=await call(done.job.fileUrl,{headers:{range:'bytes=999999-'}});assert.equal(r.status,416);
 mode='blocked';await json('/api/sg/jobs',{body:{...payload,requestId:randomUUID()}});assert.equal((await json('/api/account/usage')).imagesRemaining,2,'moderation rejection refunds member credit');assert.equal(creates,1);
 mode='rejected';await json('/api/sg/jobs',{body:{...payload,requestId:randomUUID()}});assert.equal((await json('/api/account/usage')).imagesRemaining,2,'definitive provider rejection refunds');
 mode='timeout';const uncertain=await json('/api/sg/jobs',{body:{...payload,requestId:randomUUID()}});assert.equal(uncertain.job.state,'unknown');assert.equal((await json('/api/account/usage')).imagesRemaining,1,'ambiguous submission holds credit');const count=creates;await json('/api/sg/jobs',{body:{...payload,requestId:uncertain.job.requestId}});assert.equal(creates,count);
 mode='success';env.GENERATION_DAILY_LIMIT='1';const denied=await call('/api/sg/jobs',{body:{...payload,requestId:randomUUID()}});assert.equal(denied.status,429);assert.equal((await json('/api/account/usage')).imagesRemaining,1,'failed global reservation rolls back user debit');env.GENERATION_DAILY_LIMIT='10';
 const postPayload={requestId:randomUUID(),title:'오늘도 행복하세요',consent:true,image:'data:image/png;base64,'+png.toString('base64')};const post=await json('/api/sg/publish',{body:postPayload});const mods=moderations;await json('/api/sg/publish',{body:postPayload});assert.equal(moderations,mods,'duplicate post does not repeat moderation');assert.equal((await json('/api/sg/feed',{who:1})).posts.length,1);
 assert.equal((await call('/api/sg/delete',{who:1,body:{id:post.id}})).status,403);await json('/api/sg/report',{who:1,body:{id:post.id,reason:'검토해주세요'}});assert.equal((await json('/api/sg/feed',{who:1})).posts.length,0,'reported author hidden for reporter');assert.equal((await call('/api/sg/image/'+post.id,{who:1})).status,404);
 assert.equal((await call('/api/admin/review')).status,403);env.ADMIN_ACCOUNT_IDS=ids[0];assert.equal((await json('/api/admin/review')).reports.length,1);
 await json('/api/account/feedback',{body:{category:'bug',message:'저장이 어렵습니다'}});assert.equal((await json('/api/account/feedback')).items.length,1);
 assert.equal((await call('/api/account/delete',{body:{confirmation:'아니요'}})).status,400);await json('/api/account/delete',{body:{confirmation:'탈퇴합니다'}});assert.equal((await call('/api/sg/jobs')).status,401);assert.equal((await db.query('SELECT nickname,kakao_id FROM sg_accounts WHERE id=$1',[ids[0]])).rows[0].nickname,'');assert((await db.query('SELECT * FROM sg_file_deletions')).rows.length>=2);assert.equal((await json('/api/sg/feed',{who:1})).posts.length,0);
 await db.close();console.log('PASS product: real PostgreSQL engine migrations, atomic trial/idempotency/quotas, refunds, ambiguous outcomes, isolation, ranged media, publish/report/admin, feedback, account deletion. All provider/media calls mocked; no paid requests.');
})().catch(e=>{console.error(e);process.exitCode=1});
